development:
  adapter: mysql
  database: subcrypt_pdxspursdevelopment
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: subcrypt_pdxspurstest
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: subcrypt_pdxspursproduction
  username: subcrypt_pdxspur
  password: knucklef!$t
  host: localhost
  encoding: utf8

